//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investment.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dividents
    {
        public int IdDividents { get; set; }
        public Nullable<int> IdCompany { get; set; }
        public Nullable<int> StockNeed { get; set; }
        public Nullable<int> Payment { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
