//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investment.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dividents
    {
        public int IdDividents { get; set; }
        public Nullable<int> IdCompany { get; set; }
        public Nullable<int> StockNeed { get; set; }
        public Nullable<int> Payment { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
