//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investment.ADOApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InvestmentEntities : DbContext
    {
        public InvestmentEntities()
            : base("name=InvestmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<BrokerageAccount> BrokerageAccount { get; set; }
        public virtual DbSet<Dividents> Dividents { get; set; }
        public virtual DbSet<Sector> Sector { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockMarket> StockMarket { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Company> Company { get; set; }
    }
}
