//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investment.ADOApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InvestmentEntities1 : DbContext
    {
        public InvestmentEntities1()
            : base("name=InvestmentEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<BrokerageAccount> BrokerageAccount { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Dividents> Dividents { get; set; }
        public virtual DbSet<Sector> Sector { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockMarket> StockMarket { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
