//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investment.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMarket
    {
        public int IdStockMarket { get; set; }
        public Nullable<int> IdStock { get; set; }
        public Nullable<int> LastTransaction { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
